// This file was autogenerated by lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../epiviz/datatypes/algorithms/forest.js', ['epiviz.datatypes.algorithms.Forest'], ['epiviz.datatypes.algorithms.Tree']);
goog.addDependency('../../../epiviz/datatypes/algorithms/node.js', ['epiviz.datatypes.algorithms.Node'], ['epiviz.utils.generatePseudoGUID']);
goog.addDependency('../../../epiviz/datatypes/algorithms/tree-comparer.js', ['epiviz.datatypes.algorithms.TreeComparer'], ['epiviz.datatypes.algorithms.Forest', 'epiviz.datatypes.algorithms.Node', 'epiviz.datatypes.algorithms.Tree', 'epiviz.datatypes.algorithms.TreeDiff', 'epiviz.utils.mapCombine', 'epiviz.utils.mapGet', 'epiviz.utils.mapPut']);
goog.addDependency('../../../epiviz/datatypes/algorithms/tree-diff.js', ['epiviz.datatypes.algorithms.TreeDiff'], []);
goog.addDependency('../../../epiviz/datatypes/algorithms/tree.js', ['epiviz.datatypes.algorithms.Tree'], ['epiviz.datatypes.algorithms.Node']);
goog.addDependency('../../../epiviz/test/dom/node.js', ['epiviz.test.dom.Node'], ['epiviz.datatypes.algorithms.Node', 'epiviz.utils.mapCopy']);
goog.addDependency('../../../epiviz/utils/utils.js', ['epiviz.utils.generatePseudoGUID', 'epiviz.utils.mapCombine', 'epiviz.utils.mapCopy', 'epiviz.utils.mapGet', 'epiviz.utils.mapPut'], []);
