// This file was autogenerated by lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../epiviz/datatypes/algorithms/treeeditdist/forest.js', ['epiviz.datatypes.algorithms.treeeditdist.Forest'], ['epiviz.datatypes.algorithms.treeeditdist.Tree']);
goog.addDependency('../../../epiviz/datatypes/algorithms/treeeditdist/node.js', ['epiviz.datatypes.algorithms.treeeditdist.Node'], ['epiviz.utils.generatePseudoGUID']);
goog.addDependency('../../../epiviz/datatypes/algorithms/treeeditdist/tree-comparer.js', ['epiviz.datatypes.algorithms.treeeditdist.TreeComparer'], ['epiviz.datatypes.algorithms.treeeditdist.Forest', 'epiviz.datatypes.algorithms.treeeditdist.Node', 'epiviz.datatypes.algorithms.treeeditdist.Tree', 'epiviz.datatypes.algorithms.treeeditdist.TreeDiff', 'epiviz.utils.mapCombine', 'epiviz.utils.mapGet', 'epiviz.utils.mapPut']);
goog.addDependency('../../../epiviz/datatypes/algorithms/treeeditdist/tree-diff.js', ['epiviz.datatypes.algorithms.treeeditdist.TreeDiff'], []);
goog.addDependency('../../../epiviz/datatypes/algorithms/treeeditdist/tree.js', ['epiviz.datatypes.algorithms.treeeditdist.Tree'], ['epiviz.datatypes.algorithms.treeeditdist.Node']);
goog.addDependency('../../../epiviz/test/dom/node.js', ['epiviz.test.dom.Node'], ['epiviz.datatypes.algorithms.treeeditdist.Node', 'epiviz.utils.mapCopy']);
goog.addDependency('../../../epiviz/utils/utils.js', ['epiviz.utils.generatePseudoGUID', 'epiviz.utils.mapCombine', 'epiviz.utils.mapCopy', 'epiviz.utils.mapGet', 'epiviz.utils.mapPut'], []);
